// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBig2FFW-T162bcJi5u4JSbn8AlSfnwCWg',
    appId: '1:408306176065:web:75fc04c2da6a293fdab6c0',
    messagingSenderId: '408306176065',
    projectId: 'ai-career-decision-maker',
    authDomain: 'ai-career-decision-maker.firebaseapp.com',
    storageBucket: 'ai-career-decision-maker.firebasestorage.app',
    measurementId: 'G-NDFD7RG31V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPgv6bL4o3t31Ze5cTD0L3MbVhs8jsg7c',
    appId: '1:408306176065:android:879db1dbc18efd9edab6c0',
    messagingSenderId: '408306176065',
    projectId: 'ai-career-decision-maker',
    storageBucket: 'ai-career-decision-maker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5Sc1ICLSmPKudDpUvspyz1sTM_UdGlw',
    appId: '1:408306176065:ios:91de533fdc069e54dab6c0',
    messagingSenderId: '408306176065',
    projectId: 'ai-career-decision-maker',
    storageBucket: 'ai-career-decision-maker.firebasestorage.app',
    iosBundleId: 'com.example.aiCybershield',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5Sc1ICLSmPKudDpUvspyz1sTM_UdGlw',
    appId: '1:408306176065:ios:91de533fdc069e54dab6c0',
    messagingSenderId: '408306176065',
    projectId: 'ai-career-decision-maker',
    storageBucket: 'ai-career-decision-maker.firebasestorage.app',
    iosBundleId: 'com.example.aiCybershield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBig2FFW-T162bcJi5u4JSbn8AlSfnwCWg',
    appId: '1:408306176065:web:4eecfe444804833adab6c0',
    messagingSenderId: '408306176065',
    projectId: 'ai-career-decision-maker',
    authDomain: 'ai-career-decision-maker.firebaseapp.com',
    storageBucket: 'ai-career-decision-maker.firebasestorage.app',
    measurementId: 'G-NYSETFT030',
  );
}
